
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

# Links: 4K Monitor (DP-6)
monitor=DP-6,3840x2160@143.96,0x0,1.5

# Rechts: Full HD Monitor (HDMI-A-4), mittig zum 4K
# 2160px Höhe vom 4K, FHD hat 1080px → 2160 - 1080 = 1080px / 2 = 540px Offset
monitor=HDMI-A-4,1920x1080@60,2560x180,1

# Optional: Workspaces fixieren
workspace=1,monitor:DP-6
workspace=2,monitor:HDMI-A-4

